### ISSUE TITLE
Escape Key Support

### ISSUE THREAD

**Issue by X4** [laktek/jQuery-Smart-Auto-Complete#1]
I think supporting the loosing of the list-focus through a hit of a button would be nice to have.

**Comment by stryju** [comment]
quick fix for that is to add esc key support in <code>this.each</code> loop:

add this around line 429:

<pre><code>        else if (ev.keyCode == '27'){
                    $(options.context).trigger('itemSelect');
                    return false;
        }</code></pre>


keep in mind this will trigger <code>itemSelect</code> event!
