### ISSUE TITLE
Why set inline styles on the text field?

### ISSUE THREAD

**Issue by gscottolson** [laktek/jQuery-Smart-Auto-Complete#10]
Specifically, why set "background: #FFF" (line 114)?

Why not capture the original bg color of the text field and use this when clearing the field?

**Comment by nuwansh** [comment]
Here is the quick fix for this issue. 

1) replace this in line 233:

``` javascript
background: $(context).css("background")
```

2) and remove the 113, 114 line of code and replace as follows, 

``` javascript
var type_ahead_field = $(this.context).prev(".smart_autocomplete_type_ahead_field");
      $(this.context).css({ background: type_ahead_field.css("background") });
      type_ahead_field.remove();
```
