### ISSUE TITLE
Boldface typed text in search results

### ISSUE THREAD

**Issue by Improvisu** [laktek/jQuery-Smart-Auto-Complete#2]
It would be nice if we could boldface the searched text in the results, so for example, if we had typed "cat" into the query field, the results would be:

```
<ul>
  <li><em>Cat</em>ch-22</li>
  <li><em>Cat</em>cher in the Rye</li>
  <li>The <em>Cat</em> in the Hat</li>
  <li>Felix the <em>Cat</em></li>
</ul>
```

To turn this one it could be one simple option:

```
emphasis: true
```

Great job with this by the way.

**Comment by laktek** [comment]
Using the `resultFormatter` option, you can easily add highlighting to specific portion of a result. 

I've added a new example (Example 7) to the [demo page](http://laktek.github.com/jQuery-Smart-Auto-Complete/demo/index.html), which shows how do it.

I avoided adding an option for this as there was no clear common use case. On many instances, how and what you want to highlight depend on the context.

**Comment by Improvisu** [comment]
Thanks. That helps. I see what you mean about no clear common use case. I ended up going with the Quicksilver algorithm and with that you can't really use highlighting except for those with a score of 1.
