### ISSUE TITLE
forceSelect not working properly

### ISSUE THREAD

**Issue by stryju** [laktek/jQuery-Smart-Auto-Complete#3]
input keeps on being set to null value after hitting enter

my solution ( worked fine ):

<code>$.event.special.itemSelect</code> misses check if <code>forceSelect</code> is enabled or <code>selected_value</code> is set

so line 291  with <code>$(context).val(selected_value);</code>

should become <code>(options.forceSelect || selected_value) && $(context).val(selected_value);</code>

this fix worked just fine for me

**Comment by laktek** [comment]
`forceSelect` will set the value only when you loose focus on the field without selecting a value.

If you enable `typeAhead` option, it will fill the field with the first best matching result  when you press enter.

**Comment by stryju** [comment]
imo <code>typeAhead</code> should set it to mest matching after user presses <codeEnter</code> or <code>right arrow</code>, forcing the selected value should occur only when <code>forceSelect</code> is enabled ...

**Comment by laktek** [comment]
That's how it's currently happening. I'm not clear on the issue you're
experiencing.
