### ISSUE TITLE
lack of triggering "change" event

### ISSUE THREAD

**Issue by stryju** [laktek/jQuery-Smart-Auto-Complete#4]
after item form suggested items is selected.

binding to <code>itemSelect</code> returns previous value of input (before setting it to selected item's value)

proposition of fix:
- add option <code>triggerChange:false</code>
- add <code></code> to <code$.event.special.itemSelect</code> default function <code>options.triggerChange && $(context).trigger('change');</code>

**Comment by laktek** [comment]
Since the value of the field changes when you select an item, default browser event should trigger. In which browser you tried?

**Comment by stryju** [comment]
chrome 10.0.640.151
