### ISSUE TITLE
error: a.compareDocumentPosition is not a function

### ISSUE THREAD

**Issue by zackd** [laktek/jQuery-Smart-Auto-Complete#6]
Hi,  just trying out the plugin, but getting errors...  also finding the same errors @ the github_instant demo 

tested in firefox3.6, firefox 4.

to reproduce: 

load the demo @ http://laktek.github.com/jQuery-Smart-Auto-Complete/demo/github_instant
click into search_field 
- error (firebug): 
  " a.compareDocumentPosition is not a function      jquery.min.js (line 16) "

**Comment by nuwansh** [comment]
The ticket (http://bugs.jquery.com/ticket/7297) is well describe and provide good solution for Firefox jQuery contains method error. 

To fix this issue in jQuery Smart Auto Complete plugin just replace 478 and 479 lines as follows, 

``` javascript
 var elemIsParent  = $(options.resultsContainer, ev.target).size();
 if(ev.target == options.resultsContainer || ev.target == options.context || elemIsParent == 1) return
```
